services:
  dev:
    build: .
    image: "nubim-be-dev"
    ports:
      - "80:8080"
    environment:
      - PROFILE=dev
    env_file:
      - ./.env

  prod:
    build: .
    image: "nubim-be-prod"
    ports:
      - "443:8080"
    environment:
      - PROFILE=prod
    env_file:
      - ./.env
