spring:
  datasource:
    url: jdbc:postgresql://${LOCAL_DB_HOST}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #multipart
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: info


#aws
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${LOCAL_AWS_USER_ACCESS_KEY}
      secret-key: ${LOCAL_AWS_USER_SECRET_KEY}
    s3:
      bucket: ${LOCAL_AWS_S3_NAME}
    stack:
      auto: false
