spring:
  application:
    name: "nubim"
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  #oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_URI}
            scope:
              - profile
              - email
              # Google People API, V1
              # 테스트 단계 에서는 생략하고 진행
              # - https://www.googleapis.com/auth/user.birthday.read
              # - https://www.googleapis.com/auth/user.gender.read
              # - https://www.googleapis.com/auth/user.phonenumbers.read
          apple:
            client-id: ${APPLE_OAUTH_CLIENT_ID}
            redirect-uri: ${APPLE_OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          google:
            # 사용자에게 항상 로그인할 계정을 선택하게 함
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

  #multipart
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #aws
  cloud:
    aws:
      region:
        static: ap-northeast-2
      #      credentials:
      #        access-key: ${AWS_ACCESS_KEY_ID}
      #        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_NAME}
      stack:
        auto: false

#apple
apple:
  key-id: ${APPLE_KEY_ID}
  team-id: ${APPLE_TEAM_ID}
  private-key: ${APPLE_PRIVATE_KEY}

#jwt
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1000 * 60 * 60 ( 1 hour )
  refresh-expiration: 604800000 # 1000 * 60 * 60 * 24 * 7 ( 1 week )

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}