name: dev Repository Push Deploy
run-name: "dev Deploy: Trigger by ${{ github.actor }}"
env:
  AWS_DEFAULT_REGION: ap-northeast-2

on:
  push:
    branches:
      - dev
      - chore/setup-cd
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Make short commit sha
      - name: short-sha
        uses: benjlevesque/short-sha@v3.0

      # Display push info
      - name: Display Push information
        run: |
          echo "Push Repository: ${{ github.ref_name }}"
          echo "Push Commit Id ${{ env.SHA }}"
      
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS credentials
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # AWS ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build and Push Docker Image
      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_DEV_REPOSITORY }}
          IMAGE_TAG: ${{ env.SHA }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY

