name: Pull Request Test
run-name: "Build and Test: Trigger by ${{ github.actor }}"

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    services:
      postgres:
        image: postgres:16.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.LOCAL_DB_NAME }}
          POSTGRES_USER: ${{ secrets.LOCAL_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.LOCAL_DB_PASSWORD }}
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Display PR info
      - name: Display PR information
        run: |
          echo "Pull Request from: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request to: ${{ github.event.pull_request.base.ref }}"
          echo "Pull Request author: ${{ github.event.pull_request.user.login }}"  

      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      # Run build and test
      - name: Run tests and build
        run: ./gradlew build
        env:
          LOCAL_DB_HOST: ${{ secrets.LOCAL_DB_HOST }}
          LOCAL_DB_NAME: ${{ secrets.LOCAL_DB_NAME }}
          LOCAL_DB_USERNAME: ${{ secrets.LOCAL_DB_USERNAME }}
          LOCAL_DB_PASSWORD: ${{ secrets.LOCAL_DB_PASSWORD }}
          LOCAL_AWS_S3_NAME: ${{ secrets.LOCAL_AWS_S3_NAME }}
          LOCAL_AWS_USER_ACCESS_KEY: ${{ secrets.LOCAL_AWS_USER_ACCESS_KEY }}
          LOCAL_AWS_USER_SECRET_KEY: ${{ secrets.LOCAL_AWS_USER_SECRET_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
          DEV_JWT_SECRET_KEY: ${{ secrets.DEV_JWT_SECRET_KEY }}